In [1]:
import pandas as pd

In [49]:
pokemons = pd.read_csv('Pokemon.csv', index_col='#')
pokemons

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
#,,,,,,,,,,,,
1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [5]:
#get nubers for each group
pokemons['Type 1'].value_counts()

Type 1
Water       112
Normal       98
Grass        70
Bug          69
Psychic      57
Fire         52
Electric     44
Rock         44
Dragon       32
Ground       32
Ghost        32
Dark         31
Poison       28
Steel        27
Fighting     27
Ice          24
Fairy        17
Flying        4
Name: count, dtype: int64

In [7]:
#group values by column
poke_groups = pokemons.groupby(by='Type 1')

In [9]:
#return groups with indicies as a value
poke_groups.groups

{'Bug': [10, 11, 12, 13, 14, 15, 15, 46, 47, 48, 49, 123, 127, 127, 165, 166, 167, 168, 193, 204, 205, 212, 212, 213, 214, 214, 265, 266, 267, 268, 269, 283, 284, 290, 291, 292, 313, 314, 401, 402, 412, 413, 413, 413, 414, 415, 416, 469, 540, 541, 542, 543, 544, 545, 557, 558, 588, 589, 595, 596, 616, 617, 632, 636, 637, 649, 664, 665, 666], 'Dark': [197, 198, 215, 228, 229, 229, 261, 262, 302, 302, 359, 359, 430, 461, 491, 509, 510, 559, 560, 570, 571, 624, 625, 629, 630, 633, 634, 635, 686, 687, 717], 'Dragon': [147, 148, 149, 334, 334, 371, 372, 373, 373, 380, 380, 381, 381, 384, 384, 443, 444, 445, 445, 610, 611, 612, 621, 643, 644, 646, 646, 646, 704, 705, 706, 718], 'Electric': [25, 26, 81, 82, 100, 101, 125, 135, 145, 172, 179, 180, 181, 181, 239, 243, 309, 310, 310, 311, 312, 403, 404, 405, 417, 462, 466, 479, 479, 479, 479, 479, 479, 522, 523, 587, 602, 603, 604, 642, 642, 694, 695, 702], 'Fairy': [35, 36, 173, 175, 176, 209, 210, 468, 669, 670, 671, 682, 683, 684, 685, 700, 716], 'Fighting': [56, 57, 66, 67, 68, 106, 107, 236, 237, 296, 297, 307, 308, 308, 447, 448, 448, 532, 533, 534, 538, 539, 619, 620, 674, 675, 701], 'Fire': [4, 5, 6, 6, 6, 37, 38, 58, 59, 77, 78, 126, 136, 146, 155, 156, 157, 218, 219, 240, 244, 250, 255, 256, 257, 257, 322, 323, 323, 324, 390, 391, 392, 467, 485, 498, 499, 500, 513, 514, 554, 555, 555, 631, 653, 654, 655, 662, 663, 667, 668, 721], 'Flying': [641, 641, 714, 715], 'Ghost': [92, 93, 94, 94, 200, 353, 354, 354, 355, 356, 425, 426, 429, 442, 477, 487, 487, 562, 563, 607, 608, 609, 708, 709, 710, 710, 710, 710, 711, 711, 711, 711], 'Grass': [1, 2, 3, 3, 43, 44, 45, 69, 70, 71, 102, 103, 114, 152, 153, 154, 182, 187, 188, 189, 191, 192, 252, 253, 254, 254, 273, 274, 275, 285, 286, 315, 331, 332, 357, 387, 388, 389, 406, 407, 420, 421, 455, 459, 460, 460, 465, 470, 492, 492, 495, 496, 497, 511, 512, 546, 547, 548, 549, 556, 590, 591, 597, 598, 640, 650, 651, 652, 672, 673], 'Ground': [27, 28, 50, 51, 104, 105, 111, 112, 207, 231, 232, 328, 329, 330, 343, 344, 383, 383, 449, 450, 464, 472, 529, 530, 551, 552, 553, 618, 622, 623, 645, 645], 'Ice': [124, 144, 220, 221, 225, 238, 361, 362, 362, 363, 364, 365, 378, 471, 473, 478, 582, 583, 584, 613, 614, 615, 712, 713], 'Normal': [16, 17, 18, 18, 19, 20, 21, 22, 39, 40, 52, 53, 83, 84, 85, 108, 113, 115, 115, 128, 132, 133, 137, 143, 161, 162, 163, 164, 174, 190, 203, 206, 216, 217, 233, 234, 235, 241, 242, 263, 264, 276, 277, 287, 288, 289, 293, 294, 295, 298, 300, 301, 327, 333, 335, 351, 352, 396, 397, 398, 399, 400, 424, 427, 428, 428, 431, 432, 440, 441, 446, 463, 474, 486, 493, 504, 505, 506, 507, 508, 519, 520, 521, 531, 531, 572, 573, 585, 586, 626, 627, 628, 648, 648, 659, 660, 661, 676], 'Poison': [23, 24, 29, 30, 31, 32, 33, 34, 41, 42, 88, 89, 109, 110, 169, 316, 317, 336, 434, 435, 451, 452, 453, 454, 568, 569, 690, 691], 'Psychic': [63, 64, 65, 65, 96, 97, 122, 150, 150, 150, 151, 177, 178, 196, 201, 202, 249, 251, 280, 281, 282, 282, 325, 326, 358, 360, 386, 386, 386, 386, 433, 439, 475, 475, 480, 481, 482, 488, 494, 517, 518, 527, 528, 561, 574, 575, 576, 577, 578, 579, 605, 606, 677, 678, 678, 720, 720], 'Rock': [74, 75, 76, 95, 138, 139, 140, 141, 142, 142, 185, 246, 247, 248, 248, 299, 337, 338, 345, 346, 347, 348, 377, 408, 409, 410, 411, 438, 476, 524, 525, 526, 566, 567, 639, 688, 689, 696, 697, 698, 699, 703, 719, 719], 'Steel': [208, 208, 227, 303, 303, 304, 305, 306, 306, 374, 375, 376, 376, 379, 385, 436, 437, 483, 599, 600, 601, 638, 679, 680, 681, 681, 707], 'Water': [7, 8, 9, 9, 54, 55, 60, 61, 62, 72, 73, 79, 80, 80, 86, 87, 90, 91, 98, 99, 116, 117, 118, 119, 120, 121, 129, 130, 130, 131, 134, 158, 159, 160, 170, 171, 183, 184, 186, 194, 195, 199, 211, 222, 223, 224, 226, 230, 245, 258, 259, 260, 260, 270, 271, 272, 278, 279, 318, 319, 319, 320, 321, 339, 340, 341, 342, 349, 350, 366, 367, 368, 369, 370, 382, 382, 393, 394, 395, 418, 419, 422, 423, 456, 457, 458, 484, 489, 490, 501, 502, 503, 515, 516, 535, 536, 537, 550, 564, 565, ...]}

In [13]:
#get group by refering to type
poke_groups.get_group('Grass').head(10)

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
#,,,,,,,,,,,,
1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
43,Oddish,Grass,Poison,320,45,50,55,75,65,30,1,False
44,Gloom,Grass,Poison,395,60,65,70,85,75,40,1,False
45,Vileplume,Grass,Poison,490,75,80,85,110,90,50,1,False
69,Bellsprout,Grass,Poison,300,50,75,35,70,30,40,1,False
70,Weepinbell,Grass,Poison,390,65,90,50,85,45,55,1,False
71,Victreebel,Grass,Poison,490,80,105,65,100,70,70,1,False

In [19]:
#only need to create group once to reuse
poke_groups.get_group('Fire').head(10)

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
#,,,,,,,,,,,,
4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False
6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False
6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False
37,Vulpix,Fire,NaN,299,38,41,40,50,65,65,1,False
38,Ninetales,Fire,NaN,505,73,76,75,81,100,100,1,False
58,Growlithe,Fire,NaN,350,55,70,45,70,50,60,1,False
59,Arcanine,Fire,NaN,555,90,110,80,100,80,95,1,False
77,Ponyta,Fire,NaN,410,50,85,55,65,65,90,1,False

In [25]:
#its easier to perform pivot_tables with groups
#pokemons.pivot_table(index='Type 1', aggfunc='mean').round(2)

In [29]:
poke_groups.mean(numeric_only=True).round(2)

,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Type 1,,,,,,,,,
Bug,378.93,56.88,70.97,70.72,53.87,64.80,61.68,3.22,0.00
Dark,445.74,66.81,88.39,70.23,74.65,69.52,76.16,4.03,0.06
Dragon,550.53,83.31,112.12,86.38,96.84,88.84,83.03,3.88,0.38
Electric,443.41,59.80,69.09,66.30,90.02,73.70,84.50,3.27,0.09
Fairy,413.18,74.12,61.53,65.71,78.53,84.71,48.59,4.12,0.06
Fighting,416.44,69.85,96.78,65.93,53.11,64.70,66.07,3.37,0.00
Fire,458.08,69.90,84.77,67.77,88.98,72.21,74.44,3.21,0.10
Flying,485.00,70.75,78.75,66.25,94.25,72.50,102.50,5.50,0.50
Ghost,439.56,64.44,73.78,81.19,79.34,76.47,64.34,4.19,0.06
Grass,421.14,67.27,73.21,70.80,77.50,70.43,61.93,3.36,0.04
Ground,437.50,73.78,95.75,84.84,56.47,62.75,63.91,3.16,0.12
Ice,433.46,72.00,72.75,71.42,77.54,76.29,63.46,3.54,0.08
Normal,401.68,77.28,73.47,59.85,55.82,63.72,71.55,3.05,0.02
Poison,399.14,67.25,74.68,68.82,60.43,64.39,63.57,2.54,0.00
Psychic,475.95,70.63,71.46,67.68,98.40,86.28,81.49,3.39,0.25
Rock,453.75,65.36,92.86,100.80,63.34,75.48,55.91,3.45,0.09
Steel,487.70,65.22,92.70,126.37,67.52,80.63,55.26,3.85,0.15
Water,430.46,72.06,74.15,72.95,74.81,70.52,65.96,2.86,0.04

In [35]:
#return specific data
poke_groups.get_group('Grass').mean(numeric_only=True).round(2)

Total         421.14
HP             67.27
Attack         73.21
Defense        70.80
Sp. Atk        77.50
Sp. Def        70.43
Speed          61.93
Generation      3.36
Legendary       0.04
dtype: float64

In [39]:
#groupby wih more than one column
poke_groups =pokemons.groupby(by=['Type 1', 'Type 2'], dropna=False)
poke_groups

In [41]:
#return groups with indicies as a value with 2 elements as key
poke_groups.groups

{('Bug', 'Electric'): [595, 596], ('Bug', 'Fighting'): [214, 214], ('Bug', 'Fire'): [636, 637], ('Bug', 'Flying'): [12, 123, 127, 165, 166, 193, 267, 284, 291, 414, 415, 416, 469, 666], ('Bug', 'Ghost'): [292], ('Bug', 'Grass'): [46, 47, 413, 540, 541, 542], ('Bug', 'Ground'): [290, 413], ('Bug', 'Poison'): [13, 14, 15, 15, 48, 49, 167, 168, 269, 543, 544, 545], ('Bug', 'Rock'): [213, 557, 558], ('Bug', 'Steel'): [205, 212, 212, 413, 589, 632, 649], ('Bug', 'Water'): [283], ('Bug', nan): [10, 11, 127, 204, 265, 266, 268, 313, 314, 401, 402, 412, 588, 616, 617, 664, 665], ('Dark', 'Dragon'): [633, 634, 635], ('Dark', 'Fighting'): [559, 560], ('Dark', 'Fire'): [228, 229, 229], ('Dark', 'Flying'): [198, 430, 629, 630, 717], ('Dark', 'Ghost'): [302, 302], ('Dark', 'Ice'): [215, 461], ('Dark', 'Psychic'): [686, 687], ('Dark', 'Steel'): [624, 625], ('Dark', nan): [197, 261, 262, 359, 359, 491, 509, 510, 570, 571], ('Dragon', 'Electric'): [644], ('Dragon', 'Fairy'): [334], ('Dragon', 'Fire'): [643], ('Dragon', 'Flying'): [149, 334, 373, 373, 384, 384], ('Dragon', 'Ground'): [443, 444, 445, 445, 718], ('Dragon', 'Ice'): [646, 646, 646], ('Dragon', 'Psychic'): [380, 380, 381, 381], ('Dragon', nan): [147, 148, 371, 372, 610, 611, 612, 621, 704, 705, 706], ('Electric', 'Dragon'): [181], ('Electric', 'Fairy'): [702], ('Electric', 'Fire'): [479], ('Electric', 'Flying'): [145, 479, 587, 642, 642], ('Electric', 'Ghost'): [479], ('Electric', 'Grass'): [479], ('Electric', 'Ice'): [479], ('Electric', 'Normal'): [694, 695], ('Electric', 'Steel'): [81, 82, 462], ('Electric', 'Water'): [479], ('Electric', nan): [25, 26, 100, 101, 125, 135, 172, 179, 180, 181, 239, 243, 309, 310, 310, 311, 312, 403, 404, 405, 417, 466, 522, 523, 602, 603, 604], ('Fairy', 'Flying'): [176, 468], ('Fairy', nan): [35, 36, 173, 175, 209, 210, 669, 670, 671, 682, 683, 684, 685, 700, 716], ('Fighting', 'Dark'): [675], ('Fighting', 'Flying'): [701], ('Fighting', 'Psychic'): [307, 308, 308], ('Fighting', 'Steel'): [448, 448], ('Fighting', nan): [56, 57, 66, 67, 68, 106, 107, 236, 237, 296, 297, 447, 532, 533, 534, 538, 539, 619, 620, 674], ('Fire', 'Dragon'): [6], ('Fire', 'Fighting'): [256, 257, 257, 391, 392, 499, 500], ('Fire', 'Flying'): [6, 6, 146, 250, 662, 663], ('Fire', 'Ground'): [322, 323, 323], ('Fire', 'Normal'): [667, 668], ('Fire', 'Psychic'): [555, 655], ('Fire', 'Rock'): [219], ('Fire', 'Steel'): [485], ('Fire', 'Water'): [721], ('Fire', nan): [4, 5, 37, 38, 58, 59, 77, 78, 126, 136, 155, 156, 157, 218, 240, 244, 255, 324, 390, 467, 498, 513, 514, 554, 555, 631, 653, 654], ('Flying', 'Dragon'): [714, 715], ('Flying', nan): [641, 641], ('Ghost', 'Dark'): [442], ('Ghost', 'Dragon'): [487, 487], ('Ghost', 'Fire'): [607, 608, 609], ('Ghost', 'Flying'): [425, 426], ('Ghost', 'Grass'): [708, 709, 710, 710, 710, 710, 711, 711, 711, 711], ('Ghost', 'Poison'): [92, 93, 94, 94], ('Ghost', nan): [200, 353, 354, 354, 355, 356, 429, 477, 562, 563], ('Grass', 'Dark'): [274, 275, 332], ('Grass', 'Dragon'): [254], ('Grass', 'Fairy'): [546, 547], ('Grass', 'Fighting'): [286, 640, 652], ('Grass', 'Flying'): [187, 188, 189, 357, 492], ('Grass', 'Ground'): [389], ('Grass', 'Ice'): [459, 460, 460], ('Grass', 'Poison'): [1, 2, 3, 3, 43, 44, 45, 69, 70, 71, 315, 406, 407, 590, 591], ('Grass', 'Psychic'): [102, 103], ('Grass', 'Steel'): [597, 598], ('Grass', nan): [114, 152, 153, 154, 182, 191, 192, 252, 253, 254, 273, 285, 331, 387, 388, 420, 421, 455, 465, 470, 492, 495, 496, 497, 511, 512, 548, 549, 556, 650, 651, 672, 673], ('Ground', 'Dark'): [551, 552, 553], ('Ground', 'Dragon'): [329, 330], ('Ground', 'Electric'): [618], ('Ground', 'Fire'): [383], ('Ground', 'Flying'): [207, 472, 645, 645], ('Ground', 'Ghost'): [622, 623], ('Ground', 'Psychic'): [343, 344], ('Ground', 'Rock'): [111, 112, 464], ('Ground', 'Steel'): [530], ('Ground', nan): [27, 28, 50, 51, 104, 105, 231, 232, 328, 383, 449, 450, 529], ('Ice', 'Flying'): [144, 225], ('Ice', 'Ghost'): [478], ('Ice', 'Ground'): [220, 221, 473], ('Ice', 'Psychic'): [124, 238], ('Ice', 'Water'): [363, 364, 365], ('Ice', nan): [361, 362, 362, 378, 471, 582, 583, 584, 613, 614, 615, 712, 713], ('Normal', 'Fairy'): [39, 40, 174, 298, 531], ('Normal', 'Fighting'): [428, 648], ('Normal', 'Flying'): [16, 17, 18, 18, 21, 22, 83, 84, 85, 163, 164, 276, 277, 333, 396, 397, 398, 441, 519, 520, 521, 627, 628, 661], ('Normal', 'Grass'): [585, 586], ('Normal', 'Ground'): [660], ('Normal', 'Psychic'): [203, 648], ('Normal', 'Water'): [400], ...}

In [45]:
#using groups to perform operations
poke_max = poke_groups.max(),round(2)
poke_max

(                                    Name  Total   HP  Attack  Defense  \
 Type 1 Type 2
 Bug    Electric                   Joltik    472   70      77       60
        Fighting  HeracrossMega Heracross    600   80     185      115
        Fire                    Volcarona    550   85      85       65
        Flying                    Yanmega    600   86     155      120
        Ghost                    Shedinja    236    1      90       45
 ...                                  ...    ...  ...     ...      ...
 Water  Poison                 Tentacruel    515   80      95       75
        Psychic                   Starmie    590   95      75      180
        Rock                     Tirtouga    495  100     108      133
        Steel                    Empoleon    530   84      86       88
        NaN                     Wartortle    770  170     150      120

                  Sp. Atk  Sp. Def  Speed  Generation  Legendary
 Type 1 Type 2
 Bug    Electric       97       60    108           5      False
        Fighting       40      105     85           2      False
        Fire          135      105    100           5      False
        Flying        116      110    160           6      False
        Ghost          30       30     40           3      False
 ...                  ...      ...    ...         ...        ...
 Water  Poison         80      120    100           2      False
        Psychic       130      110    115           2      False
        Rock           83       85     55           5      False
        Steel         111      101     60           4      False
        NaN           180      160    115           6       True

 [154 rows x 10 columns],
 2)

In [55]:
#get values for subtype
#poke_max.loc['Grass'].sort_values(by='Total', ascending=False)

In [53]:
#using the agg function with groups
pokemons.groupby('Type 1').agg({'Total': ['max', 'min', 'mean']}).round(2)

         Total
           max  min    mean
Type 1
Bug        600  194  378.93
Dark       680  220  445.74
Dragon     780  300  550.53
Electric   610  205  443.41
Fairy      680  218  413.18
Fighting   625  210  416.44
Fire       680  250  458.08
Flying     580  245  485.00
Ghost      680  275  439.56
Grass      630  180  421.14
Ground     770  265  437.50
Ice        580  250  433.46
Normal     720  190  401.68
Poison     535  245  399.14
Psychic    780  198  475.95
Rock       700  280  453.75
Steel      700  300  487.70
Water      770  200  430.46

In [57]:
#with uliple groups
poke_groups = pokemons.groupby(by=['Type 1', 'Type 2'], dropna=False)
poke_groups

In [59]:
poke_groups.agg({'Total': ['max', 'min','mean']}).round(2)

                Total
                  max  min    mean
Type 1 Type 2
Bug    Electric   472  319  395.50
       Fighting   600  500  550.00
       Fire       550  360  455.00
       Flying     600  244  419.50
       Ghost      236  236  236.00
...               ...  ...     ...
Water  Poison     515  335  426.67
       Psychic    590  315  481.00
       Rock       495  355  428.75
       Steel      530  530  530.00
       NaN        770  200  413.75

[154 rows x 3 columns]