In [1]:
import pandas as pd

In [181]:
pokemons = pd.read_csv('Pokemon.csv', index_col='#')
pokemons

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
#,,,,,,,,,,,,
1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [7]:
pokemons.info()

<class 'pandas.core.frame.DataFrame'>
Index: 800 entries, 1 to 721
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        800 non-null    object
 1   Type 1      800 non-null    object
 2   Type 2      414 non-null    object
 3   Total       800 non-null    int64
 4   HP          800 non-null    int64
 5   Attack      800 non-null    int64
 6   Defense     800 non-null    int64
 7   Sp. Atk     800 non-null    int64
 8   Sp. Def     800 non-null    int64
 9   Speed       800 non-null    int64
 10  Generation  800 non-null    int64
 11  Legendary   800 non-null    bool
dtypes: bool(1), int64(8), object(3)
memory usage: 75.8+ KB

In [9]:
#get info on dataset
pokemons.describe().round()

       Total     HP  Attack  Defense  Sp. Atk  Sp. Def  Speed  Generation
count  800.0  800.0   800.0    800.0    800.0    800.0  800.0       800.0
mean   435.0   69.0    79.0     74.0     73.0     72.0   68.0         3.0
std    120.0   26.0    32.0     31.0     33.0     28.0   29.0         2.0
min    180.0    1.0     5.0      5.0     10.0     20.0    5.0         1.0
25%    330.0   50.0    55.0     50.0     50.0     50.0   45.0         2.0
50%    450.0   65.0    75.0     70.0     65.0     70.0   65.0         3.0
75%    515.0   80.0   100.0     90.0     95.0     90.0   90.0         5.0
max    780.0  255.0   190.0    230.0    194.0    230.0  180.0         6.0

In [13]:
#describe the info that is not numeric
pokemons.describe(exclude=['int', 'float'])

             Name Type 1  Type 2 Legendary
count         800    800     414       800
unique        800     18      18         2
top     Bulbasaur  Water  Flying     False
freq            1    112      97       735

In [25]:
#create column for length of name
pokemons['name_length'] = pokemons['Name'].apply(len)
pokemons

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,name_length
#,,,,,,,,,,,,,
1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,9
2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,7
3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,8
3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,21
4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...
719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True,7
719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True,19
720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True,19
720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True,18
721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True,9

In [27]:
#delete name length coloumn
del pokemons['name_length']
pokemons

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
#,,,,,,,,,,,,
1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [29]:
#function to determine strength
def strength(attack: int) -> str:
    if attack > 150:
        return 'Strong'
    elif attack > 100:
        return 'Average'
    else:
        return 'Weak'

In [39]:
#populate strength column calling above function using .apply()
pokemons['Strength'] = pokemons['Attack'].apply(strength)
pokemons

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Strength
#,,,,,,,,,,,,,
1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,Weak
2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,Weak
3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,Weak
3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,Weak
4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False,Weak
...,...,...,...,...,...,...,...,...,...,...,...,...,...
719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True,Weak
719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True,Strong
720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True,Average
720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True,Strong
721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True,Average

In [43]:
pokemons.value_counts('Strength')

Strength
Weak       630
Average    152
Strong      18
Name: count, dtype: int64

In [57]:
#.apply() using multiple columns
def score(row):
    attack: int = row['Attack']
    defense: int = row['Defense']
    speed: int = row['Speed']

    return sum([attack, defense, speed])

In [61]:
#create new column using above function
pokemons['Score'] = pokemons.apply(score, axis=1)
pokemons

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Strength,Score
#,,,,,,,,,,,,,,
1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,Weak,143
2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,Weak,185
3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,Weak,245
3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,Weak,303
4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False,Weak,160
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True,Weak,300
719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True,Strong,380
720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True,Average,240
720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True,Strong,300
721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True,Average,300

In [65]:
#using lamdas with apply, shortens each name to 5 chars
short_name = pokemons['Name'].apply(lambda x: x[:5])
pokemons.insert(1, 'Short', short_name)
pokemons

,Name,Short,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Strength,Score
#,,,,,,,,,,,,,,,
1,Bulbasaur,Bulba,Grass,Poison,318,45,49,49,65,65,45,1,False,Weak,143
2,Ivysaur,Ivysa,Grass,Poison,405,60,62,63,80,80,60,1,False,Weak,185
3,Venusaur,Venus,Grass,Poison,525,80,82,83,100,100,80,1,False,Weak,245
3,VenusaurMega Venusaur,Venus,Grass,Poison,625,80,100,123,122,120,80,1,False,Weak,303
4,Charmander,Charm,Fire,NaN,309,39,52,43,60,50,65,1,False,Weak,160
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
719,Diancie,Dianc,Rock,Fairy,600,50,100,150,100,150,50,6,True,Weak,300
719,DiancieMega Diancie,Dianc,Rock,Fairy,700,50,160,110,160,110,110,6,True,Strong,380
720,HoopaHoopa Confined,Hoopa,Psychic,Ghost,600,80,110,60,150,130,70,6,True,Average,240
720,HoopaHoopa Unbound,Hoopa,Psychic,Dark,680,80,160,60,170,130,80,6,True,Strong,300
721,Volcanion,Volca,Fire,Water,600,80,110,120,130,90,70,6,True,Average,300

In [73]:
#map(), maps series, replace with new values
pokemons['Legendary'] = pokemons['Legendary'].map({False: 'No', True: 'True'})
pokemons

,Name,Short,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Strength,Score
#,,,,,,,,,,,,,,,
1,Bulbasaur,Bulba,Grass,Poison,318,45,49,49,65,65,45,1,No,Weak,143
2,Ivysaur,Ivysa,Grass,Poison,405,60,62,63,80,80,60,1,No,Weak,185
3,Venusaur,Venus,Grass,Poison,525,80,82,83,100,100,80,1,No,Weak,245
3,VenusaurMega Venusaur,Venus,Grass,Poison,625,80,100,123,122,120,80,1,No,Weak,303
4,Charmander,Charm,Fire,NaN,309,39,52,43,60,50,65,1,No,Weak,160
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
719,Diancie,Dianc,Rock,Fairy,600,50,100,150,100,150,50,6,True,Weak,300
719,DiancieMega Diancie,Dianc,Rock,Fairy,700,50,160,110,160,110,110,6,True,Strong,380
720,HoopaHoopa Confined,Hoopa,Psychic,Ghost,600,80,110,60,150,130,70,6,True,Average,240
720,HoopaHoopa Unbound,Hoopa,Psychic,Dark,680,80,160,60,170,130,80,6,True,Strong,300
721,Volcanion,Volca,Fire,Water,600,80,110,120,130,90,70,6,True,Average,300

In [81]:
#not specifying all values will cause the not specifoed to become NaN
pokemons['Generation'].map({1: 'First'})

#
1      First
2      First
3      First
3      First
4      First
       ...
719      NaN
719      NaN
720      NaN
720      NaN
721      NaN
Name: Generation, Length: 800, dtype: object

In [83]:
#applymap(), apply funcion throughout dataframe
pokemons.applymap(type)

C:\Users\Paul\AppData\Local\Temp\ipykernel_27136\1883027447.py:2: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  pokemons.applymap(type)

,Name,Short,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Strength,Score
#,,,,,,,,,,,,,,,
1,<class 'str'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'str'>,<class 'str'>,<class 'int'>
2,<class 'str'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'str'>,<class 'str'>,<class 'int'>
3,<class 'str'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'str'>,<class 'str'>,<class 'int'>
3,<class 'str'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'str'>,<class 'str'>,<class 'int'>
4,<class 'str'>,<class 'str'>,<class 'str'>,<class 'float'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'str'>,<class 'str'>,<class 'int'>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
719,<class 'str'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'str'>,<class 'str'>,<class 'int'>
719,<class 'str'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'str'>,<class 'str'>,<class 'int'>
720,<class 'str'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'str'>,<class 'str'>,<class 'int'>
720,<class 'str'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'str'>,<class 'str'>,<class 'int'>
721,<class 'str'>,<class 'str'>,<class 'str'>,<class 'str'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'int'>,<class 'str'>,<class 'str'>,<class 'int'>

In [91]:
#use applymap to change all values o strings nd apply uppercase
def uppercase(var: str) -> str:
    return var.upper()

In [95]:
pokemons = pokemons.applymap(str)
pokemons.applymap(uppercase)
#pokemons.info()

C:\Users\Paul\AppData\Local\Temp\ipykernel_27136\745495103.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  pokemons = pokemons.applymap(str)
C:\Users\Paul\AppData\Local\Temp\ipykernel_27136\745495103.py:2: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  pokemons.applymap(uppercase)

,Name,Short,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Strength,Score
#,,,,,,,,,,,,,,,
1,BULBASAUR,BULBA,GRASS,POISON,318,45,49,49,65,65,45,1,NO,WEAK,143
2,IVYSAUR,IVYSA,GRASS,POISON,405,60,62,63,80,80,60,1,NO,WEAK,185
3,VENUSAUR,VENUS,GRASS,POISON,525,80,82,83,100,100,80,1,NO,WEAK,245
3,VENUSAURMEGA VENUSAUR,VENUS,GRASS,POISON,625,80,100,123,122,120,80,1,NO,WEAK,303
4,CHARMANDER,CHARM,FIRE,NAN,309,39,52,43,60,50,65,1,NO,WEAK,160
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
719,DIANCIE,DIANC,ROCK,FAIRY,600,50,100,150,100,150,50,6,TRUE,WEAK,300
719,DIANCIEMEGA DIANCIE,DIANC,ROCK,FAIRY,700,50,160,110,160,110,110,6,TRUE,STRONG,380
720,HOOPAHOOPA CONFINED,HOOPA,PSYCHIC,GHOST,600,80,110,60,150,130,70,6,TRUE,AVERAGE,240
720,HOOPAHOOPA UNBOUND,HOOPA,PSYCHIC,DARK,680,80,160,60,170,130,80,6,TRUE,STRONG,300
721,VOLCANION,VOLCA,FIRE,WATER,600,80,110,120,130,90,70,6,TRUE,AVERAGE,300

In [97]:
#get length of all strings
pokemons.applymap(len)

C:\Users\Paul\AppData\Local\Temp\ipykernel_27136\3930869891.py:2: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  pokemons.applymap(len)

,Name,Short,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Strength,Score
#,,,,,,,,,,,,,,,
1,9,5,5,6,3,2,2,2,2,2,2,1,2,4,3
2,7,5,5,6,3,2,2,2,2,2,2,1,2,4,3
3,8,5,5,6,3,2,2,2,3,3,2,1,2,4,3
3,21,5,5,6,3,2,3,3,3,3,2,1,2,4,3
4,10,5,4,3,3,2,2,2,2,2,2,1,2,4,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
719,7,5,4,5,3,2,3,3,3,3,2,1,4,4,3
719,19,5,4,5,3,2,3,3,3,3,3,1,4,6,3
720,19,5,7,5,3,2,3,2,3,3,2,1,4,7,3
720,18,5,7,4,3,2,3,2,3,3,2,1,4,6,3
721,9,5,4,5,3,2,3,3,3,2,2,1,4,7,3

In [101]:
pokemons

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
#,,,,,,,,,,,,
1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [105]:
#rturn evry data  type of the dataframe
pokemons.dtypes

Name          object
Type 1        object
Type 2        object
Total          int64
HP             int64
Attack         int64
Defense        int64
Sp. Atk        int64
Sp. Def        int64
Speed          int64
Generation     int64
Legendary       bool
dtype: object

In [111]:
#use astype() to convert data types, NaN cant be converted to numbers
#these examples change form int64 to smaller more appropriate types saving memory
pokemons['Generation'] = pokemons['Generation'].astype('int8')
pokemons['Total'] = pokemons['Total'].astype('int16')
pokemons.info()

<class 'pandas.core.frame.DataFrame'>
Index: 800 entries, 1 to 721
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        800 non-null    object
 1   Type 1      800 non-null    object
 2   Type 2      414 non-null    object
 3   Total       800 non-null    int16
 4   HP          800 non-null    int64
 5   Attack      800 non-null    int64
 6   Defense     800 non-null    int64
 7   Sp. Atk     800 non-null    int64
 8   Sp. Def     800 non-null    int64
 9   Speed       800 non-null    int64
 10  Generation  800 non-null    int8
 11  Legendary   800 non-null    bool
dtypes: bool(1), int16(1), int64(6), int8(1), object(3)
memory usage: 65.6+ KB

In [113]:
#change True and False to 1 and 0
pokemons['Legendary'] = pokemons['Legendary'].astype('int8')
pokemons

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
#,,,,,,,,,,,,
1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,0
2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,0
3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,0
3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,0
4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,1
719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,1
720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,1
720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,1
721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,1

In [115]:
pokemons.info

<bound method DataFrame.info of                       Name   Type 1  Type 2  Total  HP  Attack  Defense  \
#
1                Bulbasaur    Grass  Poison    318  45      49       49
2                  Ivysaur    Grass  Poison    405  60      62       63
3                 Venusaur    Grass  Poison    525  80      82       83
3    VenusaurMega Venusaur    Grass  Poison    625  80     100      123
4               Charmander     Fire     NaN    309  39      52       43
..                     ...      ...     ...    ...  ..     ...      ...
719                Diancie     Rock   Fairy    600  50     100      150
719    DiancieMega Diancie     Rock   Fairy    700  50     160      110
720    HoopaHoopa Confined  Psychic   Ghost    600  80     110       60
720     HoopaHoopa Unbound  Psychic    Dark    680  80     160       60
721              Volcanion     Fire   Water    600  80     110      120

     Sp. Atk  Sp. Def  Speed  Generation  Legendary
#
1         65       65     45           1          0
2         80       80     60           1          0
3        100      100     80           1          0
3        122      120     80           1          0
4         60       50     65           1          0
..       ...      ...    ...         ...        ...
719      100      150     50           6          1
719      160      110    110           6          1
720      150      130     70           6          1
720      170      130     80           6          1
721      130       90     70           6          1

[800 rows x 12 columns]>

In [119]:
#replacing single values using .replace()
pokemons['Legendary'].replace({True : 'Yes', False : 'No'}, inplace=True)
pokemons

C:\Users\Paul\AppData\Local\Temp\ipykernel_27136\2456919691.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  pokemons['Legendary'].replace({True : 'Yes', False : 'No'}, inplace=True)

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
#,,,,,,,,,,,,
1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,No
2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,No
3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,No
3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,No
4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,No
...,...,...,...,...,...,...,...,...,...,...,...,...
719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,Yes
719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,Yes
720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,Yes
720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,Yes
721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,Yes

In [123]:
#only replace one value
pokemons['Generation'].replace({1 : 'First'}, inplace=True)
pokemons

C:\Users\Paul\AppData\Local\Temp\ipykernel_27136\1109820398.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  pokemons['Generation'].replace({1 : 'First'}, inplace=True)

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
#,,,,,,,,,,,,
1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,First,No
2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,First,No
3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,First,No
3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,First,No
4,Charmander,Fire,NaN,309,39,52,43,60,50,65,First,No
...,...,...,...,...,...,...,...,...,...,...,...,...
719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,Yes
719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,Yes
720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,Yes
720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,Yes
721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,Yes

In [137]:
#use .replace() on entire dataframe
pokemons.replace({'Grass': '!', 'First' : '!!', 'Yes' : '!!!'})

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
#,,,,,,,,,,,,
1,Bulbasaur,!,Poison,318,45,49,49,65,65,45,1,False
2,Ivysaur,!,Poison,405,60,62,63,80,80,60,1,False
3,Venusaur,!,Poison,525,80,82,83,100,100,80,1,False
3,VenusaurMega Venusaur,!,Poison,625,80,100,123,122,120,80,1,False
4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [139]:
#use .where(), if condition false reterns False
pokemons.where(pokemons['Generation'] == 2)

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
#,,,,,,,,,,,,
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
719,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
719,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
720,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
720,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
721,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [145]:
#use dropna to show filtered
pokemons.where(pokemons['Generation'] == 2).dropna()

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
#,,,,,,,,,,,,
163,Hoothoot,Normal,Flying,262.0,60.0,30.0,30.0,36.0,56.0,50.0,2.0,False
164,Noctowl,Normal,Flying,442.0,100.0,50.0,50.0,76.0,96.0,70.0,2.0,False
165,Ledyba,Bug,Flying,265.0,40.0,20.0,30.0,40.0,80.0,55.0,2.0,False
166,Ledian,Bug,Flying,390.0,55.0,35.0,50.0,55.0,110.0,85.0,2.0,False
167,Spinarak,Bug,Poison,250.0,40.0,60.0,40.0,40.0,40.0,30.0,2.0,False
168,Ariados,Bug,Poison,390.0,70.0,90.0,70.0,60.0,60.0,40.0,2.0,False
169,Crobat,Poison,Flying,535.0,85.0,90.0,80.0,70.0,80.0,130.0,2.0,False
170,Chinchou,Water,Electric,330.0,75.0,38.0,38.0,56.0,56.0,67.0,2.0,False
171,Lanturn,Water,Electric,460.0,125.0,58.0,58.0,76.0,76.0,67.0,2.0,False
174,Igglybuff,Normal,Fairy,210.0,90.0,30.0,15.0,40.0,20.0,15.0,2.0,False
176,Togetic,Fairy,Flying,405.0,55.0,40.0,85.0,80.0,105.0,40.0,2.0,False
177,Natu,Psychic,Flying,320.0,40.0,50.0,45.0,70.0,45.0,70.0,2.0,False
178,Xatu,Psychic,Flying,470.0,65.0,75.0,70.0,95.0,70.0,95.0,2.0,False
181,AmpharosMega Ampharos,Electric,Dragon,610.0,90.0,95.0,105.0,165.0,110.0,45.0,2.0,False
183,Marill,Water,Fairy,250.0,70.0,20.0,50.0,20.0,50.0,40.0,2.0,False
184,Azumarill,Water,Fairy,420.0,100.0,50.0,80.0,60.0,80.0,50.0,2.0,False
187,Hoppip,Grass,Flying,250.0,35.0,35.0,40.0,35.0,55.0,50.0,2.0,False
188,Skiploom,Grass,Flying,340.0,55.0,45.0,50.0,45.0,65.0,80.0,2.0,False
189,Jumpluff,Grass,Flying,460.0,75.0,55.0,70.0,55.0,95.0,110.0,2.0,False
193,Yanma,Bug,Flying,390.0,65.0,65.0,45.0,75.0,45.0,95.0,2.0,False
194,Wooper,Water,Ground,210.0,55.0,45.0,45.0,25.0,25.0,15.0,2.0,False
195,Quagsire,Water,Ground,430.0,95.0,85.0,85.0,65.0,65.0,35.0,2.0,False
198,Murkrow,Dark,Flying,405.0,60.0,85.0,42.0,85.0,42.0,91.0,2.0,False
199,Slowking,Water,Psychic,490.0,95.0,75.0,80.0,100.0,110.0,30.0,2.0,False
203,Girafarig,Normal,Psychic,455.0,70.0,80.0,65.0,90.0,65.0,85.0,2.0,False
205,Forretress,Bug,Steel,465.0,75.0,90.0,140.0,60.0,60.0,40.0,2.0,False
207,Gligar,Ground,Flying,430.0,65.0,75.0,105.0,35.0,65.0,85.0,2.0,False
208,Steelix,Steel,Ground,510.0,75.0,85.0,200.0,55.0,65.0,30.0,2.0,False
208,SteelixMega Steelix,Steel,Ground,610.0,75.0,125.0,230.0,55.0,95.0,30.0,2.0,False
211,Qwilfish,Water,Poison,430.0,65.0,95.0,75.0,55.0,55.0,85.0,2.0,False
212,Scizor,Bug,Steel,500.0,70.0,130.0,100.0,55.0,80.0,65.0,2.0,False
212,ScizorMega Scizor,Bug,Steel,600.0,70.0,150.0,140.0,65.0,100.0,75.0,2.0,False
213,Shuckle,Bug,Rock,505.0,20.0,10.0,230.0,10.0,230.0,5.0,2.0,False
214,Heracross,Bug,Fighting,500.0,80.0,125.0,75.0,40.0,95.0,85.0,2.0,False
214,HeracrossMega Heracross,Bug,Fighting,600.0,80.0,185.0,115.0,40.0,105.0,75.0,2.0,False
215,Sneasel,Dark,Ice,430.0,55.0,95.0,55.0,35.0,75.0,115.0,2.0,False
219,Magcargo,Fire,Rock,410.0,50.0,50.0,120.0,80.0,80.0,30.0,2.0,False
220,Swinub,Ice,Ground,250.0,50.0,50.0,40.0,30.0,30.0,50.0,2.0,False
221,Piloswine,Ice,Ground,450.0,100.0,100.0,80.0,60.0,60.0,50.0,2.0,False
222,Corsola,Water,Rock,380.0,55.0,55.0,85.0,65.0,85.0,35.0,2.0,False
225,Delibird,Ice,Flying,330.0,45.0,55.0,45.0,65.0,45.0,75.0,2.0,False
226,Mantine,Water,Flying,465.0,65.0,40.0,70.0,80.0,140.0,70.0,2.0,False
227,Skarmory,Steel,Flying,465.0,65.0,80.0,140.0,40.0,70.0,70.0,2.0,False
228,Houndour,Dark,Fire,330.0,45.0,60.0,30.0,80.0,50.0,65.0,2.0,False
229,Houndoom,Dark,Fire,500.0,75.0,90.0,50.0,110.0,80.0,95.0,2.0,False
229,HoundoomMega Houndoom,Dark,Fire,600.0,75.0,90.0,90.0,140.0,90.0,115.0,2.0,False
230,Kingdra,Water,Dragon,540.0,75.0,95.0,95.0,95.0,95.0,85.0,2.0,False
238,Smoochum,Ice,Psychic,305.0,45.0,30.0,15.0,85.0,65.0,65.0,2.0,False
246,Larvitar,Rock,Ground,300.0,50.0,64.0,50.0,45.0,50.0,41.0,2.0,False
247,Pupitar,Rock,Ground,410.0,70.0,84.0,70.0,65.0,70.0,51.0,2.0,False
248,Tyranitar,Rock,Dark,600.0,100.0,134.0,110.0,95.0,100.0,61.0,2.0,False
248,TyranitarMega Tyranitar,Rock,Dark,700.0,100.0,164.0,150.0,95.0,120.0,71.0,2.0,False
249,Lugia,Psychic,Flying,680.0,106.0,90.0,130.0,90.0,154.0,110.0,2.0,True
250,Ho-oh,Fire,Flying,680.0,106.0,130.0,90.0,110.0,154.0,90.0,2.0,True
251,Celebi,Psychic,Grass,600.0,100.0,100.0,100.0,100.0,100.0,100.0,2.0,False

In [151]:
#use where to show placeholder where it doent match criteria, use dropna to remove
pokemons = pokemons.where(pokemons['Type 1'] == 'Grass', other=None)
pokemons.dropna()

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
#,,,,,,,,,,,,
1,Bulbasaur,Grass,Poison,318.0,45.0,49.0,49.0,65.0,65.0,45.0,1.0,False
2,Ivysaur,Grass,Poison,405.0,60.0,62.0,63.0,80.0,80.0,60.0,1.0,False
3,Venusaur,Grass,Poison,525.0,80.0,82.0,83.0,100.0,100.0,80.0,1.0,False
3,VenusaurMega Venusaur,Grass,Poison,625.0,80.0,100.0,123.0,122.0,120.0,80.0,1.0,False
43,Oddish,Grass,Poison,320.0,45.0,50.0,55.0,75.0,65.0,30.0,1.0,False
44,Gloom,Grass,Poison,395.0,60.0,65.0,70.0,85.0,75.0,40.0,1.0,False
45,Vileplume,Grass,Poison,490.0,75.0,80.0,85.0,110.0,90.0,50.0,1.0,False
69,Bellsprout,Grass,Poison,300.0,50.0,75.0,35.0,70.0,30.0,40.0,1.0,False
70,Weepinbell,Grass,Poison,390.0,65.0,90.0,50.0,85.0,45.0,55.0,1.0,False
71,Victreebel,Grass,Poison,490.0,80.0,105.0,65.0,100.0,70.0,70.0,1.0,False
102,Exeggcute,Grass,Psychic,325.0,60.0,40.0,80.0,60.0,45.0,40.0,1.0,False
103,Exeggutor,Grass,Psychic,520.0,95.0,95.0,85.0,125.0,65.0,55.0,1.0,False
187,Hoppip,Grass,Flying,250.0,35.0,35.0,40.0,35.0,55.0,50.0,2.0,False
188,Skiploom,Grass,Flying,340.0,55.0,45.0,50.0,45.0,65.0,80.0,2.0,False
189,Jumpluff,Grass,Flying,460.0,75.0,55.0,70.0,55.0,95.0,110.0,2.0,False
254,SceptileMega Sceptile,Grass,Dragon,630.0,70.0,110.0,75.0,145.0,85.0,145.0,3.0,False
274,Nuzleaf,Grass,Dark,340.0,70.0,70.0,40.0,60.0,40.0,60.0,3.0,False
275,Shiftry,Grass,Dark,480.0,90.0,100.0,60.0,90.0,60.0,80.0,3.0,False
286,Breloom,Grass,Fighting,460.0,60.0,130.0,80.0,60.0,60.0,70.0,3.0,False
315,Roselia,Grass,Poison,400.0,50.0,60.0,45.0,100.0,80.0,65.0,3.0,False
332,Cacturne,Grass,Dark,475.0,70.0,115.0,60.0,115.0,60.0,55.0,3.0,False
357,Tropius,Grass,Flying,460.0,99.0,68.0,83.0,72.0,87.0,51.0,3.0,False
389,Torterra,Grass,Ground,525.0,95.0,109.0,105.0,75.0,85.0,56.0,4.0,False
406,Budew,Grass,Poison,280.0,40.0,30.0,35.0,50.0,70.0,55.0,4.0,False
407,Roserade,Grass,Poison,515.0,60.0,70.0,65.0,125.0,105.0,90.0,4.0,False
459,Snover,Grass,Ice,334.0,60.0,62.0,50.0,62.0,60.0,40.0,4.0,False
460,Abomasnow,Grass,Ice,494.0,90.0,92.0,75.0,92.0,85.0,60.0,4.0,False
460,AbomasnowMega Abomasnow,Grass,Ice,594.0,90.0,132.0,105.0,132.0,105.0,30.0,4.0,False
492,ShayminSky Forme,Grass,Flying,600.0,100.0,103.0,75.0,120.0,75.0,127.0,4.0,True
546,Cottonee,Grass,Fairy,280.0,40.0,27.0,60.0,37.0,50.0,66.0,5.0,False
547,Whimsicott,Grass,Fairy,480.0,60.0,67.0,85.0,77.0,75.0,116.0,5.0,False
590,Foongus,Grass,Poison,294.0,69.0,55.0,45.0,55.0,55.0,15.0,5.0,False
591,Amoonguss,Grass,Poison,464.0,114.0,85.0,70.0,85.0,80.0,30.0,5.0,False
597,Ferroseed,Grass,Steel,305.0,44.0,50.0,91.0,24.0,86.0,10.0,5.0,False
598,Ferrothorn,Grass,Steel,489.0,74.0,94.0,131.0,54.0,116.0,20.0,5.0,False
640,Virizion,Grass,Fighting,580.0,91.0,90.0,72.0,90.0,129.0,108.0,5.0,True
652,Chesnaught,Grass,Fighting,530.0,88.0,107.0,122.0,74.0,75.0,64.0,6.0,False

In [155]:
#use agg() to aggregate one or more opertions
pokemons.agg({'Attack' : 'mean', 'Defense' : 'max'})

Attack      79.00125
Defense    230.00000
dtype: float64

In [161]:
 #specify muliple agg
pokemons.agg({'Attack': ['min', 'max', 'std'], 'Defense': ['min', 'max', 'mean']})

          Attack   Defense
min     5.000000    5.0000
max   190.000000  230.0000
std    32.457366       NaN
mean         NaN   73.8425

In [165]:
#return max values for all numeric
pokemons.agg('max', numeric_only=True)

Total          780
HP             255
Attack         190
Defense        230
Sp. Atk        194
Sp. Def        230
Speed          180
Generation       6
Legendary     True
dtype: object

In [179]:
#specify multiple operations
pokemons.agg(['max','min'], numeric_only=True)

TypeError: Series.max does not allow numeric_only=True with non-numeric dtypes.

In [185]:
#use copy to not affect original dataframe, creates a copy
legendary = pokemons['Legendary'].copy()
legendary

#
1      False
2      False
3      False
3      False
4      False
       ...
719     True
719     True
720     True
720     True
721     True
Name: Legendary, Length: 800, dtype: bool

In [191]:
#modify the copied and the origonal wont be changed
legendary[0:3] = '???'
legendary

#
1        ???
2        ???
3        ???
3      False
4      False
       ...
719     True
719     True
720     True
720     True
721     True
Name: Legendary, Length: 800, dtype: object

In [193]:
#original dataframe not altered
pokemons

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
#,,,,,,,,,,,,
1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True